LIB_SRC = 			\
	Acceptor.cc		\
	Channel.cc		\
	EventLoop.cc		\
	EventLoopThread.cc	\
	InetAddress.cc		\
	Poller.cc		\
	Socket.cc		\
	SocketsOps.cc		\
	Timer.cc		\
	TimerQueue.cc

BINARIES = test7 test8

all: $(BINARIES)

include ../reactor_lib.mk

test7: test7.cc
test8: test8.cc
